/**
 * Alert and notification models for system events.
 * Used by alert service and notification service.
 */
/**
 * Types of alerts that can be generated in the system.
 */
export type AlertType = 'REGIONAL_OVERLOAD' | 'METER_OUTAGE' | 'ANOMALY' | 'SYSTEM_FAILURE';
/**
 * Severity levels for alerts.
 */
export type AlertSeverity = 'INFO' | 'WARN' | 'CRITICAL';
/**
 * Represents an alert event in the system.
 * Alerts are generated by various services and consumed by notification service.
 */
export interface Alert {
    /** Unique identifier for this alert (UUID v4) */
    alertId: string;
    /** Type/category of the alert */
    type: AlertType;
    /** Severity level determining urgency and routing */
    severity: AlertSeverity;
    /** Optional geographic region associated with this alert */
    region?: string;
    /** Optional meter ID if alert is meter-specific */
    meterId?: string;
    /** Human-readable alert message */
    message: string;
    /** ISO 8601 timestamp when the alert was generated */
    timestamp: string;
    /** Whether the alert has been acknowledged by an operator */
    acknowledged?: boolean;
    /** Optional user ID of the operator who acknowledged */
    acknowledgedBy?: string;
    /** Optional timestamp of acknowledgement */
    acknowledgedAt?: string;
    /** Additional contextual data for the alert */
    metadata?: Record<string, unknown>;
}
/**
 * Alert rule configuration for automated alert generation.
 */
export interface AlertRule {
    /** Unique identifier for the rule */
    ruleId: string;
    /** Rule name */
    name: string;
    /** Type of alert this rule generates */
    alertType: AlertType;
    /** Severity of alerts generated by this rule */
    severity: AlertSeverity;
    /** Condition expression (e.g., "avgPowerKw > 80") */
    condition: string;
    /** Time window for condition evaluation in seconds */
    windowSeconds: number;
    /** Whether the rule is currently active */
    enabled: boolean;
    /** Optional region filter */
    region?: string;
}
/**
 * Type guard to check if an object is a valid Alert
 */
export declare function isAlert(obj: unknown): obj is Alert;
/**
 * Type guard to check if an alert type is valid
 */
export declare function isAlertType(value: string): value is AlertType;
/**
 * Type guard to check if a severity level is valid
 */
export declare function isAlertSeverity(value: string): value is AlertSeverity;
//# sourceMappingURL=alert.d.ts.map